### ISSUE TITLE
Unification method

### ISSUE THREAD

**Issue by richard-uk1** [toastal/either#2]
I would like a method like

```elm
mapEither : ( a -> c ) -> ( b -> c) -> Either a b -> c
```
that resolves to a type whichever way the Either is. This would be useful e.g. if `c = Html Msg` where the Either could be 2 different options for some data.

Example implementation

```elm
mapEither : ( a -> c ) -> ( b -> c ) -> Either a b -> c
mapEither mapl mapr val =
  case val of
    Either.Left vall ->
        mapl vall
    Either.Right valr ->
        mapr valr
```

do you think this could/should be in the module?

Also would you prefer another name, for example `unify`, or something else?

**Comment by toastal** [comment]
@derekdreery http://package.elm-lang.org/packages/toastal/either/latest/Either#unpack

It exists already and it has a name in line with other libraries.

**Comment by richard-uk1** [comment]
Missed that
